export const FILTER_GAMES = "FILTER_GAMES";
export const FILTER_GAMES_AND_COVERS = "FILTER_GAMES_AND_COVERS";

export const GET_RANDOM_GAME = "GET_RANDOM_GAME";
export const GET_PREFERRED_GAMES = "GET_PREFERRED_GAMES";
export const GET_ID = "GET_ID";

export const GET_SINGLE_GAME_INFO = "GET_SINGLE_GAME_INFO";

export const CHECK_AUTH = "CHECK_AUTH";

export const GET_PROFILE_DATA = "GET_PROFILE_DATA";
export const GET_USER_FOLDERS = "GET_USER_FOLDERS";
export const FETCH_GAMES_IN_FOLDER = "FETCH_GAMES_IN_FOLDER";
export const SET_NEW_FOLDER = "SET_NEW_FOLDER";
export const DELETE_GAME = "DELETE_GAME";
export const DELETE_FOLDER = "DELETE_FOLDER";

export const ADD_GAME_TO_FOLDER = "ADD_GAME_TO_FOLDER";
export const ADD_USER_RATING = "ADD_USER_RATING";
export const FETCH_USER_RATING = "FETCH_USER_RATING";
