export const CHANGE_SEARCH_FIELD = "CHANGE_SEARCH_FIELD";
export const SELECT_GENRES = "SELECT_GENRES";
export const SELECT_PLATFORMS = "SELECT_PLATFORMS";
export const SELECT_YEAR = "SELECT_YEAR";
export const SELECT_RATING = "SELECT_RATING";
export const SELECT_POPULARITY = "SELECT_POPULARITY";
export const CHANGE_PAGE_FORWARD = "CHANGE_PAGE_FORWARD";
export const CHANGE_PAGE_BACK = "CHANGE_PAGE_BACK";
